services:
  postgres:
    image: postgres:17-alpine
    container_name: gomi-db-container
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -p $DB_PORT -d $DB_NAME"]
      interval: 1s
      timeout: 5s
      retries: 30
    environment:
      - PGPORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - gomi-network

networks:
  gomi-network:
    driver: bridge

volumes:
  postgres:
    name: gomi-db-volume

